### PR TITLE
test CI pipeline for Client Build check

### PR DESCRIPTION
**Pull request by XiaoQuark**
This PR is created to test the Client Build Check GitHub Actions workflow. 

**Changes**
Introduced a minimal placeholder change in the client's README to trigger the GitHub Actions workflow for testing purposes.

**Testing**
The workflow should:
- Automatically run upon creating this PR.
- Execute npm run build in the client directory.
- Mark the PR as failed if the build encounters errors.
- Observing this PR to confirm that the workflow behaves as expected.

### CODE REVIEW

**Comment by XiaoQuark** [comment]
image

The Client Build Check workflow started successfully after creating this pull request.

**Review by Homvi — APPROVED** [review]
Looks like it works

**Comment by XiaoQuark** [comment]
image

Confirm check has failed correctly

**Comment by XiaoQuark** [comment]
PR was created to test the new CI workflow. The build was intentionally set to fail to verify the system's response. Now closing PR as it served its purpose.

**Pull request closed without merging**
